name: cci_app
description: "Aplicación oficial de CCI San Pedro Sula para eventos, información y notificaciones."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  animated_text_kit: ^4.2.2
  lottie: ^3.1.0
  youtube_player_iframe: ^5.2.1
  google_nav_bar: ^5.0.6
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.2.5
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4
  webview_flutter: ^4.0.5
  http: ^1.1.0
  firebase_core:
    ^3.6.0
  firebase_messaging:
    ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/logo.png
    - assets/images/home_screen.png
    - assets/images/menu.png
  # SF Pro Display es una fuente nativa de iOS, no necesita archivos de fuente
  # fonts:
  #   - family: SF Pro Display
  #     fonts:
  #       - asset: assets/fonts/SFProDisplay-Regular.ttf
  #       - asset: assets/fonts/SFProDisplay-Bold.ttf
  #         weight: 700
